### ISSUE TITLE
buefy Navbar Error --> TypeError: this.genNavbar is not a function

### ISSUE THREAD

**Issue by JWaldowPE** [buefy/buefy#4133]
### Overview of the problem

**Buefy** version: buefy-next  0.9.23
**Vuejs** version: [3.3.4]
**OS/Browser**:Windows11/Chrome

### Description

Not sure if it even is an error within buefy-next but after migrating my vue.js 2 project to 3 I encountered an error with the navbar we were using before. Within the mount of my application it throws an error saying: "TypeError: this.genNavbar is not a function":
Stacktrace:
`
Uncaught (in promise) TypeError: this.genNavbar is not a function
    at Proxy.render (navbar.js:389:1)
    at renderComponentRoot (vue.runtime.esm-bundler.js:2693:1)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.runtime.esm-bundler.js:8710:1)
    at ReactiveEffect.run (vue.runtime.esm-bundler.js:429:1)
    at instance.update (vue.runtime.esm-bundler.js:8844:1)
    at setupRenderEffect (vue.runtime.esm-bundler.js:8852:1)
    at mountComponent (vue.runtime.esm-bundler.js:8618:1)
    at processComponent (vue.runtime.esm-bundler.js:8570:1)
    at patch (vue.runtime.esm-bundler.js:8045:1)
    at mountChildren (vue.runtime.esm-bundler.js:8289:1)`

I tried to use the b-navbar diretly in my App but I am getting the same Error basically: 
`vue.runtime.esm-bundler.js:1458  [Vue warn]: Property "genNavbar" was accessed during render but is not defined on instance. 
  at <BNavbar> 
  at <App>`
![image](https://github.com/ntohq/buefy-metadata-transfer/assets/138443788/cb4e33de-9b68-4828-b584-99d988bb65e5)

I am not completely sure this error has something to do with the buefy package - but maybe someone can help me since I really need this package to work or else we have to stay on vue.js 2.
If it is specific to my project I will try to provide a codepen or something - but maybe someone can help me

### Steps to reproduce
Not sure if it is happening in new Projects as well 
Vue.js@3
Webpack@5
Mount App and try to add <b-navbar>

### Expected behavior

Like the behavior in vue.js 2

### Actual behavior

Error after/while mounting the application
