### ISSUE TITLE
Buefy with SASS customizations does not compile in its latest version 0.9.4

### ISSUE THREAD

**Issue by fungiboletus** [buefy/buefy#3126]
### Overview of the problem

**Buefy** version: 0.9.4
**Vuejs** version: 2.6.12
**OS/Browser**: GNU/Linux - Ubuntu / Not relevant

### Description

Following [the customization guide for Buefy](https://buefy.org/documentation/customization), it appears that the version `0.9.4` doesn't compile anymore. The version `0.9.3` does compiles correctly.

### Steps to reproduce

1. Use buefy following [the customization guide](https://buefy.org/documentation/customization).

### Expected behavior

Buefy compiles correctly.

### Actual behavior

You get a compilation error:

```
Syntax Error: SassError: Undefined variable: "$form-colors".
        on line 8 of node_modules/buefy/src/scss/components/_checkbox.scss
        from line 5 of node_modules/buefy/src/scss/buefy.scss
        from line 89 of src/assets/css/mystuff.scss
>> $checkbox-colors: $form-colors !default;
   ------------------^
```

**Comment by fungiboletus** [comment]
Sorry, it was another dependency depending on bulma 0.9.0 and not 0.9.1.
